
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - docker compose down
    # Supprimer silencieusement si existe, ignorer l'erreur si n'existe pas
    - docker rmi radio_web_platform_frontend:latest 2>/dev/null || true
  script:
    - docker compose build
        --build-arg APP_PORT=${APP_PORT}
        --build-arg AUTH_SECRET=${AUTH_SECRET}
        --build-arg AUTH_URL=${AUTH_URL}
        --build-arg NEXT_PUBLIC_BASE_URL="${NEXT_PUBLIC_BASE_URL}"
        --build-arg NODE_ENV=${NODE_ENV}

    # - echo "Compile complete."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - docker compose up -d
