services:
  radio-web-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=${APP_PORT}
        - NODE_ENV=${NODE_ENV}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - AUTH_SECRET=${AUTH_SECRET}
        - AUTH_URL=${AUTH_URL}
    container_name: radio-web-platform-frontend
    image: radio_web_platform_frontend:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    restart: unless-stopped
    networks:
      - traefik_proxy_traefik-network
    labels:
      - "traefik.enable=true"
      # Service
      - "traefik.http.services.radio-web-platform-frontend.loadbalancer.server.port=${APP_PORT}"

      # Router
      - "traefik.http.routers.radio-web-platform-frontend.rule=Host(`radio.frontend.ecocloud.tn`)"
      - "traefik.http.routers.radio-web-platform-frontend.entrypoints=websecure"
      - "traefik.http.routers.radio-web-platform-frontend.tls=true"
      - "traefik.http.routers.radio-web-platform-frontend.tls.certresolver=letsencrypt"

      # Link router to service
      - "traefik.http.routers.radio-web-platform-frontend.service=radio-web-platform-frontend"

      # Middleware for HTTPS redirect (recommandé)
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.radio-web-platform-frontend-http.rule=Host(`radio.frontend.ecocloud.tn`)"
      - "traefik.http.routers.radio-web-platform-frontend-http.entrypoints=web"
      - "traefik.http.routers.radio-web-platform-frontend-http.middlewares=redirect-to-https"


networks:
  traefik_proxy_traefik-network:
    external: true
